---
- name: Check for ActiveMQ installation 
  stat:
    path: "{{ activemq.path }}/activemq-{{ activemq.version }}"
  register: activemq_result

- name: Installing ActiveMQ
  debug:
    msg: "Fetching ActiveMQ Install Handlers"
  notify: "Install ActiveMQ"
  when: activemq_result.stat.exists == False
  
- name: Check for Sym Link
  stat:
    path: "{{ activemq.path }}/activemq"
  register: sym_result

- name: Making Sym Link
  debug:
    msg: "Fetching Sym Link Handlers"
  notify: "Create ActiveMQ Sym Link"
  when: (sym_result.stat.islnk is defined and sym_result.stat.islnk) == False

- name: Chown Dir
  file:
    dest: "{{ activemq.path }}/activemq-{{ activemq.version }}"
    owner: activemq
    group: activemq
    recurse: yes

- name: Set ActiveMQ Home
  lineinfile:
    path: /home/activemq/.bash_profile
    line: export ACTIVEMQ_HOME=/opt/activemq/
  
- name: Add ActiveMQ bin to path
  lineinfile:
    path: /home/activemq/.bash_profile
    line: export PATH=$PATH:$ACTIVEMQ_HOME/bin
