---
- name: Install JDK
  yum: name=java-1.8.0-openjdk state=latest
- name: Set Java Home
  shell: echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" | sudo tee -a /etc/profile && source /etc/profile
