---
- name: Download ActiveMQ
  get_url:
    url: "https://archive.apache.org/dist/activemq/{{activemq.version}}/apache-activemq-{{activemq.version}}-bin.tar.gz"
    dest: "~/activemq-{{activemq.version}}.tar.gz"
  listen: "Install ActiveMQ"
  when: activemq_result.stat.exists == False

- name: Extract ActiveMQ
  shell: "tar -zxvf ~/activemq-{{activemq.version}}.tar.gz -C {{ activemq.path }}"
  listen: "Install ActiveMQ"
  when: activemq_result.stat.exists == False

- name: Clean artifact
  file:
    state: absent
    path: /home/centos/activemq-5.14.tar.gz
  listen: "Install ActiveMQ"
  when: activemq_result.stat.exists == False

- name: Remove Bad Sym Link
  file:
    state: absent
    path: "{{ activemq.path }}/activemq"
  listen: "Create ActiveMQ Sym Link"

- name: Create symlink
  file:
    src: /opt/apache-activemq-5.14.3
    dest: /opt/activemq
    state: link
  listen: "Create ActiveMQ Sym Link"
