---
# handlers file for /etc/ansible/roles/activemq
- name: ActiveMQ download
  get_url:
    url: "https://archive.apache.org/dist/activemq/{{activemq.version}}/apache-activemq-{{activemq.version}}-bin.tar.gz"
    dest: "~/activemq.tar.gz"

- name: ActiveMQ dir setup
  file:
    path: /opt/activemq
    state: directory

# Unarchive module was buggy.  Requires further investigation
- name: ActiveMQ extract
  shell: tar -zxvf ~/activemq.tar.gz --strip-components=1 -C /opt/activemq
  args:
    warn: false

- name: ActiveMQ clean artifact
  file:
    state: absent
    path: ~/activemq.tar.gz

- name: ActiveMQ chown dir
  file:
    dest: "{{ activemq.path }}/activemq"
    owner: activemq
    group: activemq
    recurse: yes

# IP table module was buggy.  Requires further investigation
- name: ActiveMQ open iptable
  shell: "iptables -I INPUT -p tcp -m tcp --dport {{ item }} -j ACCEPT"
  loop:
    - 8161
    - 61613
    - 61614
    - 61616
    - 1883

- name: Supervisord restart
  service: name=supervisord state=restarted

